{{- if ne (len .Values.configFiles) 0 }}
{{- $releaseName := .Release.Name }}
{{- $releaseService := .Release.Service }}
{{- range $containerPathKey,$configFileInfos := .Values.configFiles }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $containerPathKey }}
  labels:
    app: {{ template "etjob.name" $ }}
    chart: {{ template "etjob.chart" $ }}
    release: {{ $releaseName }}
    heritage: {{ $releaseService }}
    createdBy: "ETJob"
data:
{{- range $configFileKey,$configFileInfo := $configFileInfos }}
  {{ $configFileInfo.containerFileName }}: |-
{{ $configFileInfo.content | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
