# Default values for runai-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The minimal available pods to run for this Job
# project: "default"
# gpu: 0
# image: ""
# cpu: ""
# memory: ""
hostIPC: false
elastic: false
interactive: false
shm: false
localImage: false
hostNetwork: false
# labels:
#   runai/label: label
# ttlSecondsAfterFinished: 0

# will be overriden by cli argument
# environment: 
# - name3=value3
# - name4=value4

# will be merged with cli argument
# environmentDefault:
# - name=value
# - name2=value2

# serviceType: "nodeport"

# will be overriden by cli argument
# ports:
  # - '80:30001'

# will be merged with cli argument
# portsDefault:
#   - '30000:9090'
  # - 8080

# command:
#   - 'start-notebook.sh'
# args:
#   - '--NotebookApp.base_url={url}'

# node_type: ""
user: ""

# will be overriden by cli argument
# volume:
#   - /path/on/host1:/dest/container/path1

# will be merged with cli argument
# volumeDefault:
#   - /path/on/host:/dest/container/path
