apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-grafana
  namespace: arena-system
spec:
  selector:
    matchLabels:
      task: monitoring
      k8s-app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: grafana
    spec:
      containers:
        - name: grafana
          image: registry.cn-hangzhou.aliyuncs.com/acs/grafana:5.0.4-gpu-monitoring
          ports:
            - containerPort: 3000
              protocol: TCP
      volumes:
        - name: grafana-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana
  namespace: arena-system
spec:
  ports:
    - port: 80
      targetPort: 3000
  type: NodePort
  selector:
    k8s-app: grafana