apiVersion: v1
kind: Service
metadata:
  name: {{ template "tensorrt-inference-server.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "tensorrt-inference-server.chart" . }}
    app: {{ template "tensorrt-inference-server.name" . }}
    servingName: {{ .Values.servingName }}
    servingType: "trt-serving"
    servingVersion: "{{ .Values.servingVersion }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: restful-serving
      port: {{ .Values.httpPort }}
      targetPort: {{ .Values.httpPort }}
    - name: grpc-serving
      port: {{ .Values.grpcPort }}
      targetPort: {{ .Values.grpcPort }}
    - name: grpc-server
      port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
  selector:
    release: {{ .Release.Name | quote }}
    app: {{ template "tensorrt-inference-server.name" . }}