apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: job-supervisor
    {{- include "arena.labels" . | nindent 4 }}
  name: job-supervisor
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-supervisor
      {{- include "arena.labels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "arena.labels" . | nindent 8 }}
        app: job-supervisor
    spec:
      nodeSelector:
        {{- include "arena.nodeSelector" . | nindent 8 }}
        {{- include "arena.nonEdgeNodeSelector" . | nindent 8 }}
      tolerations:
      {{- include "arena.tolerateNonEdgeNodeSelector" . | nindent 6 }}
      containers:
        - command:
            - /job-supervisor
          image: {{ include "arena.imagePrefix" . }}/{{ .Values.image }}:{{ .Values.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: job-supervisor
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: job-supervisor
      serviceAccountName: job-supervisor
      terminationGracePeriodSeconds: 30