# Default values for custom-serving.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# sync mode
syncMode: git
# rsync image
rsyncImage: registry.cn-zhangjiakou.aliyuncs.com/acs/rsync:v3.1.0-aliyun
# git sync image
gitImage: registry-cn-zhangjiakou.ack.aliyuncs.com/acs/git-sync:4.4.0

image: "registry.cn-beijing.aliyuncs.com/hzx-kubeflow/evaluate_test_tensorflow1.15:1.0.3"

imagePullPolicy: Always

nodeSelector: {}

tolerations: []

affinity: {}
