{{- $workers := .Values.workers -}}
{{- $ps := .Values.ps -}}
{{- $chief := .Values.chief -}}
{{- $evaluator := .Values.evaluator -}}
{{- $total := .Values.total -}}
{{- if .Values.ps }}
{{- if .Values.hasGangScheduler }}
{{- if .Values.enableGangScheduler }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "tfjob.name" . }}
    chart: {{ template "tfjob.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if .Values.chief }}
  minAvailable: {{ add $workers $ps $chief $evaluator }}
{{- else }}
  minAvailable: {{ add $workers $ps }}
{{- end }}
  selector:
    matchLabels:
      tf_job_name: {{ .Release.Name }}
{{- end }}
{{- end }}
{{- end }}