apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tensorflow-serving.fullname" . }}-cm
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "tensorflow-serving.chart" . }}
    app: {{ template "tensorflow-serving.name" . }}
data:
{{- if .Values.modelConfigFileContent }}
  modelConfigFileContent: |
    {{ .Values.modelConfigFileContent }}
{{- end }}