{{- if ne .Values.modelConfigFileContent "" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tensorflow-serving.fullname" . }}-cm
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "tensorflow-serving.chart" . }}
    app: {{ template "tensorflow-serving.name" . }}
data:
  modelConfigFileContent: |-
{{ .Values.modelConfigFileContent | indent 4 }}
{{- end }}
